// <auto-generated />
namespace CustomerManager_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class NewChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202110181515475_NewChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
